theme = "catppuccin_mocha"

[editor]
color-modes = true
cursorline = true
bufferline = "multiple"
line-number = "relative"
scrolloff = 8

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
tab = "all"
nbsp = "all"
nnbsp = "all"
