#!/bin/sh

# Check if executable is in the PATH.
in_path() {
    command -v "$1" >/dev/null 2 >&1
}

# Check if this is a remote connection.
is_remote() {
    test -n "$SSH_CONNECTION"
}

# Get the OS type.
is_mac() {
    test $(uname) = Darwin
}

is_linux() {
    test $(uname) = Linux
}

is_zsh() {
    test $(basename $SHELL) = zsh
}

is_bash() {
    test $(basename $SHELL) = bash
}