[runtime]
auto_instantiate = true
on_cell_change = "autorun"
auto_reload = "autorun"

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = true

[formatting]
line_length = 79

[ai]
rules = ""

[experimental]

[keymap]
preset = "default"

[keymap.overrides]

[snippets]
custom_paths = []
include_default_snippets = true

[package_management]
manager = "uv"

[server]
browser = "default"
follow_symlink = false

[display]
theme = "light"
dataframes = "rich"
default_width = "full"
code_editor_font_size = 14
cell_output = "above"

[completion]
activate_on_typing = true
copilot = "github"
